.PHONY: clean All

All:
	@echo "----------Building project:[ OCVTest - Debug ]----------"
	@cd "OCVTest" && "$(MAKE)" -f  "OCVTest.mk"
clean:
	@echo "----------Cleaning project:[ OCVTest - Debug ]----------"
	@cd "OCVTest" && "$(MAKE)" -f  "OCVTest.mk" clean
